version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: always
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

